// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Calendarize",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Calendarize",
            targets: ["AppModule"],
            teamIdentifier: "3GKRDMF57X",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .magicWand),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Please allow access to camera."),
                .photoLibrary(purposeString: "Please allow access to photo library.")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/TimOliver/TOCropViewController", "2.6.1"..<"3.0.0"),
        .package(url: "https://github.com/dscyrescotti/ShuffleIt#shuffledeck", .branch("main"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "CropViewController", package: "TOCropViewController"),
                .product(name: "ShuffleDeck", package: "shuffleit#shuffledeck")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)